name: DockerComposeOnPush
on:
  push:
    branches:
      - main
jobs:
  build_run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
