name: DockerComposeOnPush
on:
  push:
    branches:
      - main
jobs:
  build_run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker compose build

      - name: up postgres and app container runs
        run: docker compose up -d